// Autogenerated by mobile build prep
export const API_BASE = typeof process !== "undefined" && process.env.API_BASE ? process.env.API_BASE : "https://api.nexaai.co.uk";
export const APP_BASE = typeof process !== "undefined" && process.env.APP_BASE ? process.env.APP_BASE : "https://app.nexaai.co.uk";
